### ISSUE TITLE
 Can't infer?

### ISSUE THREAD

**Issue by eye289475** [YasasviPeruvemba/HandwritingRecognition#1]
Is this accuracy only the recognition of MNIST numbers?
I want to recognize a local image and try it out. Is it possible to infer by adding the image etc. to the argument and executing the command?

**Comment by YasasviPeruvemba** [comment]
Yeah, it's for MNIST numbers, but if you want to try it on a custom image, initially scale it to 28*28, and just use the weights, biases from the pickle.
